name: CI

on:
  push:
    branches: [ main ]
    tags-ignore: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Debug
      run: dotnet build --no-restore

    - name: Check Format
      run: dotnet format --no-restore --verify-no-changes

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Generate Coverage Report
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:"./coverage/*/coverage.cobertura.xml" -targetdir:"./artifacts" -reporttypes:"MarkdownSummaryGithub;TextSummary"

        reportgenerator -reports:"./coverage/*/coverage.cobertura.xml" -targetdir:"./coverage_html" -reporttypes:"Html"
        tar -C coverage_html -zcf ./artifacts/coverage.tar.gz .

    - name: Report Coverage
      run: |
        cat "./artifacts/Summary.txt"
        cat "./artifacts/SummaryGithub.md" > $GITHUB_STEP_SUMMARY

    - name: Build Release
      run: dotnet build --no-restore -c Release

    - name: Create Artifacts
      run: |
        dotnet pack --no-build -c Release -o ./artifacts

        dotnet tool install -g docfx
        docfx doc/docfx.json

        CUR_DIR=$(pwd)
        REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}
        pushd "./doc/_site"
        tar -zcf "${CUR_DIR}/artifacts/help-${REPOSITORY_NAME}.tar.gz" *
        popd

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifacts-${{ runner.os }}-${{ runner.arch }}-${{ github.run_number }}
        path: artifacts/
        retention-days: 1
